dict={'size_0': 0,
 'size_1': 0,
 'size_10': 0,
 'size_100': 0,
 'size_101': 0,
 'size_102': 0,
 'size_103': 0,
 'size_104': 0,
 'size_105': 0,
 'size_106': 0,
 'size_107': 0,
 'size_108': 0,
 'size_109': 0,
 'size_11': 0,
 'size_110': 0,
 'size_111': 0,
 'size_112': 0,
 'size_113': 0,
 'size_114': 0,
 'size_115': 0,
 'size_116': 0,
 'size_117': 0,
 'size_118': 0,
 'size_119': 0,
 'size_12': 0,
 'size_120': 0,
 'size_121': 0,
 'size_122': 0,
 'size_123': 0,
 'size_124': 0,
 'size_125': 0,
 'size_126': 0,
 'size_127': 0,
 'size_128': 0,
 'size_129': 0,
 'size_13': 0,
 'size_130': 0,
 'size_131': 0,
 'size_132': 0,
 'size_133': 0,
 'size_134': 0,
 'size_135': 0,
 'size_136': 0,
 'size_137': 0,
 'size_138': 0,
 'size_139': 0,
 'size_14': 0,
 'size_140': 0,
 'size_141': 0,
 'size_142': 0,
 'size_143': 0,
 'size_144': 0,
 'size_145': 0,
 'size_146': 0,
 'size_147': 0,
 'size_148': 0,
 'size_149': 0,
 'size_15': 0,
 'size_150': 0,
 'size_151': 0,
 'size_152': 0,
 'size_153': 0,
 'size_154': 0,
 'size_155': 0,
 'size_156': 0,
 'size_157': 0,
 'size_158': 0,
 'size_159': 0,
 'size_16': 0,
 'size_160': 0,
 'size_161': 0,
 'size_162': 0,
 'size_163': 0,
 'size_164': 0,
 'size_165': 0,
 'size_166': 0,
 'size_167': 0,
 'size_168': 0,
 'size_169': 0,
 'size_17': 0,
 'size_170': 0,
 'size_171': 0,
 'size_172': 0,
 'size_173': 0,
 'size_174': 0,
 'size_175': 0,
 'size_176': 0,
 'size_177': 0,
 'size_178': 0,
 'size_179': 0,
 'size_18': 0,
 'size_180': 0,
 'size_181': 0,
 'size_182': 0,
 'size_183': 0,
 'size_184': 0,
 'size_185': 0,
 'size_186': 0,
 'size_187': 0,
 'size_188': 0,
 'size_189': 0,
 'size_19': 0,
 'size_190': 0,
 'size_191': 0,
 'size_192': 0,
 'size_193': 0,
 'size_194': 0,
 'size_195': 0,
 'size_196': 0,
 'size_197': 0,
 'size_198': 0,
 'size_199': 0,
 'size_2': 0,
 'size_20': 0,
 'size_200': 0,
 'size_201': 0,
 'size_202': 0,
 'size_203': 0,
 'size_204': 0,
 'size_205': 0,
 'size_206': 0,
 'size_207': 0,
 'size_208': 0,
 'size_209': 0,
 'size_21': 0,
 'size_210': 0,
 'size_22': 0,
 'size_23': 0,
 'size_24': 0,
 'size_25': 0,
 'size_26': 0,
 'size_27': 0,
 'size_28': 0,
 'size_29': 0,
 'size_3': 0,
 'size_30': 0,
 'size_31': 0,
 'size_32': 0,
 'size_33': 0,
 'size_34': 0,
 'size_35': 0,
 'size_36': 0,
 'size_37': 0,
 'size_38': 0,
 'size_39': 0,
 'size_4': 0,
 'size_40': 0,
 'size_41': 0,
 'size_42': 0,
 'size_43': 0,
 'size_44': 0,
 'size_45': 0,
 'size_46': 0,
 'size_47': 0,
 'size_48': 0,
 'size_49': 0,
 'size_5': 0,
 'size_50': 0,
 'size_51': 0,
 'size_52': 0,
 'size_53': 0,
 'size_54': 0,
 'size_55': 0,
 'size_56': 0,
 'size_57': 0,
 'size_58': 0,
 'size_59': 0,
 'size_6': 0,
 'size_60': 0,
 'size_61': 0,
 'size_62': 0,
 'size_63': 0,
 'size_64': 0,
 'size_65': 0,
 'size_66': 0,
 'size_67': 0,
 'size_68': 0,
 'size_69': 0,
 'size_7': 0,
 'size_70': 0,
 'size_71': 0,
 'size_72': 0,
 'size_73': 0,
 'size_74': 0,
 'size_75': 0,
 'size_76': 0,
 'size_77': 0,
 'size_78': 0,
 'size_79': 0,
 'size_8': 0,
 'size_80': 0,
 'size_81': 0,
 'size_82': 0,
 'size_83': 0,
 'size_84': 0,
 'size_85': 0,
 'size_86': 0,
 'size_87': 0,
 'size_88': 0,
 'size_89': 0,
 'size_9': 0,
 'size_90': 0,
 'size_91': 0,
 'size_92': 0,
 'size_93': 0,
 'size_94': 0,
 'size_95': 0,
 'size_96': 0,
 'size_97': 0,
 'size_98': 0,
 'size_99': 0,
 'size_L': 0,
 'size_M': 0,
 'size_S': 0,
 'size_XL': 0,
 'size_XS': 0,
 'size_no size': 0,
 'gender_boy': 0,
 'gender_girl': 0,
 'gender_unisex': 0,
 'category_accessories': 0,
 'category_bodysuits': 0,
 'category_bottoms-pants': 0,
 'category_coats-jackets': 0,
 'category_costume-wear': 0,
 'category_footwear': 0,
 'category_jumpers-knitwear': 0,
 'category_overalls-jumpsuits': 0,
 'category_pajamas': 0,
 'category_shirts-blouses': 0,
 'category_skirts-dresses': 0,
 'category_tops-tshirts': 0,
 'category_winter-overalls': 0,
 'brand_3 pommes': 0,
 'brand_8848 altitude': 0,
 'brand_a denim story': 0,
 'brand_a happy brand': 0,
 'brand_abeko': 0,
 'brand_abercrombie & fitch': 0,
 'brand_absorba': 0,
 'brand_acne studios': 0,
 'brand_adidas': 0,
 'brand_adidas golf': 0,
 'brand_adidas originals': 0,
 'brand_adidas performance': 0,
 'brand_agatha ruiz de la prada': 0,
 'brand_air jordan': 0,
 'brand_ancient greek sandals': 0,
 'brand_andy & evan': 0,
 'brand_angel & rocket': 0,
 'brand_angry birds': 0,
 'brand_angulus': 0,
 'brand_anne kurris': 0,
 'brand_antena': 0,
 'brand_anïve for the minors': 0,
 'brand_arket': 0,
 'brand_armor lux': 0,
 'brand_asics': 0,
 'brand_avengers': 0,
 "brand_bandit's girl": 0,
 'brand_bangbang copenhagen': 0,
 'brand_barbie': 0,
 'brand_barbour': 0,
 'brand_barcelona fc': 0,
 'brand_bardot junior': 0,
 'brand_barts': 0,
 'brand_batman': 0,
 'brand_beau & rooster': 0,
 'brand_beau loves': 0,
 'brand_bellybutton': 0,
 'brand_belstaff': 0,
 'brand_ben sherman': 0,
 'brand_benetton': 0,
 'brand_bergans': 0,
 'brand_bikkemberg kids': 0,
 'brand_billabong': 0,
 'brand_billieblush': 0,
 'brand_billybandit': 0,
 'brand_birkenstock': 0,
 'brand_bisgaard': 0,
 'brand_björn borg': 0,
 'brand_blankens': 0,
 'brand_blue effect': 0,
 'brand_blue seven': 0,
 'brand_blundstone': 0,
 'brand_blune': 0,
 'brand_bobo choses': 0,
 'brand_bobux': 0,
 'brand_bodyflirt': 0,
 'brand_bogs': 0,
 'brand_bonds': 0,
 'brand_bonpoint': 0,
 'brand_bonprix': 0,
 'brand_bonton': 0,
 'brand_boss': 0,
 'brand_boss kidswear': 0,
 'brand_boy london': 0,
 'brand_boys & girls': 0,
 'brand_bpc bonprix collection': 0,
 'brand_bpc selection': 0,
 'brand_burberry': 0,
 'brand_burton': 0,
 'brand_by nils': 0,
 'brand_bäbis': 0,
 'brand_búho': 0,
 'brand_calvin klein': 0,
 'brand_calvin klein jeans': 0,
 'brand_calvin klein underwear': 0,
 'brand_camano': 0,
 'brand_camper': 0,
 'brand_caramel baby & child': 0,
 'brand_caroline bosmans': 0,
 'brand_carrement beau': 0,
 'brand_carrément beau': 0,
 'brand_cars': 0,
 'brand_cars jeans': 0,
 "brand_carter's": 0,
 'brand_catimini': 0,
 'brand_cebe': 0,
 'brand_celavi': 0,
 'brand_champion': 0,
 'brand_champion rochester': 0,
 'brand_chi chi girls': 0,
 'brand_chipie': 0,
 'brand_chloé': 0,
 'brand_christina rohde': 0,
 'brand_civiliants': 0,
 'brand_claesen‘s': 0,
 'brand_clarks': 0,
 'brand_cmp': 0,
 'brand_colmar': 0,
 'brand_color kids': 0,
 'brand_columbia': 0,
 'brand_converse': 0,
 'brand_cotton on': 0,
 'brand_craft': 0,
 'brand_creamie': 0,
 'brand_cristiano ronaldo cr7': 0,
 'brand_crocs': 0,
 'brand_cyrillus': 0,
 'brand_d-xel': 0,
 'brand_d6 soul': 0,
 'brand_dc': 0,
 'brand_dc shoes': 0,
 'brand_design by kappahl': 0,
 'brand_designers, remix': 0,
 'brand_desigual': 0,
 'brand_deuter': 0,
 'brand_diadora': 0,
 'brand_didriksons': 0,
 'brand_diesel': 0,
 'brand_dim': 0,
 'brand_din sko': 0,
 'brand_disney': 0,
 'brand_disney bambi': 0,
 'brand_disney frozen': 0,
 'brand_disney mickey mouse': 0,
 'brand_disney minnie mouse': 0,
 'brand_disney pixar cars': 0,
 'brand_disney princess': 0,
 'brand_dkny': 0,
 'brand_dkny kids': 0,
 'brand_dolce & gabbana': 0,
 'brand_dolly by le petit tom': 0,
 'brand_dr kid': 0,
 'brand_dr. martens': 0,
 'brand_döll': 0,
 'brand_eastpak': 0,
 'brand_easy peasy': 0,
 'brand_ebbe': 0,
 'brand_ebbe kids': 0,
 'brand_ecco': 0,
 'brand_element': 0,
 'brand_eleven paris': 0,
 'brand_ellos kids': 0,
 'brand_ellos shoes': 0,
 'brand_elodie details': 0,
 'brand_emil i lönneberga': 0,
 'brand_emile et ida': 0,
 'brand_emma och malena': 0,
 'brand_emma och malena maternity': 0,
 'brand_emoji': 0,
 'brand_emporio armani': 0,
 'brand_emu australia': 0,
 'brand_enfant': 0,
 'brand_enter': 0,
 'brand_esprit': 0,
 'brand_esprit kids': 0,
 'brand_estore': 0,
 'brand_ewers': 0,
 'brand_fabrizio': 0,
 'brand_falke': 0,
 'brand_fashy': 0,
 'brand_fendi': 0,
 'brand_fila': 0,
 'brand_filemon kid': 0,
 'brand_filippa k': 0,
 'brand_finger in the nose': 0,
 'brand_fireman sam': 0,
 'brand_five seasons': 0,
 'brand_fixoni': 0,
 'brand_flik flak': 0,
 'brand_frank dandy': 0,
 'brand_franklin & marshall': 0,
 'brand_fred perry': 0,
 "brand_fred's world by green cotton": 0,
 'brand_friboo': 0,
 'brand_frozen': 0,
 'brand_frugi': 0,
 'brand_fub': 0,
 'brand_fusalp': 0,
 'brand_färg&form': 0,
 'brand_g-star': 0,
 'brand_gant': 0,
 'brand_gap': 0,
 'brand_garcia': 0,
 'brand_gardner and the gang': 0,
 'brand_gcds': 0,
 'brand_gebriel juno by junona': 0,
 'brand_geggamoja': 0,
 'brand_geox': 0,
 'brand_globe': 0,
 'brand_gobabygo': 0,
 'brand_golden goose': 0,
 'brand_gray label': 0,
 'brand_gro': 0,
 'brand_grunt': 0,
 'brand_guess': 0,
 'brand_gugguu': 0,
 'brand_gulliver': 0,
 'brand_h&m': 0,
 'brand_hackett aston martin racing': 0,
 'brand_hackett london': 0,
 'brand_happy girls': 0,
 'brand_happy socks': 0,
 'brand_hatley': 0,
 'brand_havaianas': 0,
 'brand_head': 0,
 'brand_hebe': 0,
 'brand_hello kitty': 0,
 'brand_helly hansen': 0,
 'brand_henri lloyd': 0,
 'brand_hestra': 0,
 'brand_hi-tec': 0,
 'brand_holly´s': 0,
 'brand_how to kiss a frog': 0,
 'brand_hugo loves tiki': 0,
 'brand_hummel': 0,
 'brand_hummel fashion': 0,
 'brand_hunter': 0,
 'brand_hust & claire': 0,
 'brand_hust&claire;': 0,
 'brand_huttelihut': 0,
 'brand_hype': 0,
 'brand_i dig denim': 0,
 'brand_icepeak': 0,
 'brand_igi natur': 0,
 'brand_igor': 0,
 'brand_il gufo': 0,
 'brand_indikidual': 0,
 'brand_isbjörn of sweden': 0,
 'brand_j.crew': 0,
 'brand_jack & jones junior': 0,
 'brand_jack wolfskin': 0,
 'brand_jacky baby': 0,
 'brand_jocko': 0,
 'brand_joha': 0,
 'brand_john baner jeanswear': 0,
 'brand_jojo maman bébé': 0,
 'brand_joma': 0,
 'brand_jordan': 0,
 'brand_jottum': 0,
 'brand_joules': 0,
 'brand_juicy couture': 0,
 'brand_junior league': 0,
 'brand_k-swiss': 0,
 'brand_kamik': 0,
 'brand_kangaroos': 0,
 'brand_kaporal': 0,
 'brand_kappa': 0,
 'brand_kardashian kids': 0,
 'brand_karl lagerfeld': 0,
 'brand_karl lagerfeld kids': 0,
 'brand_kastinger': 0,
 'brand_kavat': 0,
 'brand_keen': 0,
 'brand_kempa': 0,
 'brand_kenzo': 0,
 'brand_kickers': 0,
 'brand_kids only': 0,
 'brand_kidsbrandstore': 0,
 'brand_kidzroom': 0,
 'brand_kipling': 0,
 'brand_koolabah': 0,
 'brand_kram barnkläder': 0,
 'brand_krüger dirndl': 0,
 'brand_kuling': 0,
 'brand_la queue du chat': 0,
 'brand_lacoste': 0,
 'brand_lager157': 0,
 "brand_lands' end": 0,
 'brand_lego ninjago': 0,
 'brand_lego wear': 0,
 'brand_lemon beret': 0,
 'brand_les coyotes de paris': 0,
 'brand_les deux': 0,
 "brand_levi's": 0,
 "brand_levi's kids": 0,
 "brand_levi's®": 0,
 'brand_levis': 0,
 'brand_levis kids': 0,
 'brand_lico': 0,
 'brand_liewood': 0,
 "brand_lil'boo": 0,
 'brand_lili gaufrette': 0,
 'brand_lillelam': 0,
 'brand_lindberg': 0,
 'brand_lindberg sweden': 0,
 'brand_lindex': 0,
 'brand_linear': 0,
 'brand_little creative factory': 0,
 'brand_little eleven paris': 0,
 'brand_little jalo': 0,
 'brand_little luwi': 0,
 'brand_little man happy': 0,
 'brand_little marc jacobs': 0,
 'brand_little remix': 0,
 'brand_livly': 0,
 'brand_lmtd': 0,
 'brand_lotto': 0,
 'brand_louise misha': 0,
 'brand_lowa': 0,
 'brand_ltb': 0,
 'brand_lucky ellen': 0,
 'brand_lucy & sam': 0,
 'brand_lundmyr of sweden': 0,
 'brand_lyle & scott': 0,
 'brand_lässig': 0,
 'brand_m lindberg': 0,
 'brand_mads nørgaard': 0,
 'brand_mainio': 0,
 'brand_manchester united': 0,
 'brand_mango kids': 0,
 "brand_marc o'polo": 0,
 "brand_marc o'polo junior": 0,
 'brand_marmar copenhagen': 0,
 'brand_marmar cph': 0,
 'brand_marqy': 0,
 'brand_marqy girl': 0,
 'brand_marvel spider-man': 0,
 'brand_massimo dutti': 0,
 'brand_max collection': 0,
 'brand_maximo': 0,
 'brand_mayoral': 0,
 'brand_me too': 0,
 'brand_melissa odabash': 0,
 'brand_melton': 0,
 'brand_merrell': 0,
 'brand_mexx': 0,
 'brand_mi&u design': 0,
 'brand_michael kors': 0,
 'brand_mickey mouse': 0,
 'brand_mikk-line': 0,
 'brand_milly & willy': 0,
 'brand_mini a ture': 0,
 'brand_mini rodini': 0,
 'brand_minimalisma': 0,
 'brand_minimarket': 0,
 'brand_minions': 0,
 'brand_minnie mouse': 0,
 'brand_mint&berry girls': 0,
 'brand_mintini baby': 0,
 'brand_minymo': 0,
 'brand_mirella': 0,
 'brand_missoni kids': 0,
 'brand_mister tee': 0,
 'brand_mizuno': 0,
 'brand_modern native': 0,
 'brand_modéerska huset': 0,
 'brand_molo': 0,
 'brand_moncler': 0,
 'brand_monnalisa': 0,
 'brand_monster high': 0,
 'brand_moodie': 0,
 'brand_moschino': 0,
 'brand_moschino kids': 0,
 'brand_mothercare': 0,
 'brand_move by melton': 0,
 'brand_mp': 0,
 'brand_mp denmark': 0,
 'brand_msgm': 0,
 'brand_mumin': 0,
 'brand_mustang': 0,
 'brand_my little pony': 0,
 'brand_my only': 0,
 'brand_mói': 0,
 'brand_müsli by green cotton': 0,
 'brand_nadadelazos': 0,
 'brand_nalle puh': 0,
 'brand_name it': 0,
 'brand_nameit': 0,
 'brand_napapijri': 0,
 'brand_naturino': 0,
 'brand_neil barrett': 0,
 'brand_new balance': 0,
 'brand_new era': 0,
 'brand_new look 915 generation': 0,
 'brand_new york yankees': 0,
 'brand_newbie baby': 0,
 'brand_nike': 0,
 'brand_nike performance': 0,
 'brand_nike sportswear': 0,
 'brand_no added sugar': 0,
 'brand_no brand': 0,
 'brand_noa noa': 0,
 'brand_noa noa miniature': 0,
 'brand_nono': 0,
 'brand_nop': 0,
 'brand_noppies': 0,
 'brand_nova kids': 0,
 'brand_nova star': 0,
 'brand_noé & zoë': 0,
 'brand_noël': 0,
 'brand_nununu': 0,
 'brand_oas': 0,
 'brand_oeuf': 0,
 'brand_one day parade': 0,
 'brand_one we like': 0,
 'brand_oneill': 0,
 'brand_oshkosh': 0,
 'brand_outfit kids': 0,
 'brand_ovs': 0,
 'brand_paddington': 0,
 'brand_papu': 0,
 'brand_parajumpers': 0,
 'brand_patagonia': 0,
 'brand_patrizia pepe': 0,
 'brand_paul smith junior': 0,
 'brand_paw patrol': 0,
 'brand_pax scandinavia': 0,
 'brand_peak performance': 0,
 'brand_people wear organic': 0,
 'brand_pepe jeans': 0,
 'brand_perfect moment': 0,
 'brand_perrelli street wear': 0,
 'brand_petit bateau': 0,
 'brand_petit by sofie schnoor': 0,
 'brand_petit monster': 0,
 'brand_petitbo': 0,
 'brand_petrol industries': 0,
 'brand_petter & kajsa': 0,
 'brand_phister & philina': 0,
 'brand_pick & pack': 0,
 'brand_pinko up': 0,
 'brand_pinkoholic': 0,
 'brand_pippi': 0,
 'brand_pippi långstrump': 0,
 'brand_pj masks': 0,
 'brand_play': 0,
 'brand_play up': 0,
 'brand_playshoes': 0,
 'brand_polarn o. pyret': 0,
 'brand_polarnopyret': 0,
 'brand_polo ralph lauren': 0,
 "brand_pom d'api": 0,
 'brand_popupshop': 0,
 'brand_primigi': 0,
 'brand_produkt': 0,
 'brand_puma': 0,
 'brand_pure pure by bauer': 0,
 'brand_quiksilver': 0,
 'brand_rainbow': 0,
 'brand_rains': 0,
 'brand_ralph lauren': 0,
 'brand_ralph lauren kids': 0,
 'brand_raspberry plum': 0,
 'brand_raspberry republic': 0,
 'brand_re-gen': 0,
 'brand_redskins': 0,
 'brand_reebok': 0,
 'brand_regatta': 0,
 'brand_reima': 0,
 'brand_replay': 0,
 'brand_retour': 0,
 'brand_retour jeans': 0,
 'brand_revival': 0,
 'brand_riot club': 0,
 'brand_rip curl': 0,
 'brand_river island': 0,
 'brand_robeez': 0,
 'brand_roberto cavalli': 0,
 'brand_rosemunde': 0,
 'brand_roxy': 0,
 'brand_rubber duck': 0,
 'brand_rylee + cru': 0,
 'brand_s.oliver': 0,
 'brand_sail racing': 0,
 'brand_salomon': 0,
 'brand_salto': 0,
 'brand_sanetta': 0,
 'brand_sanetta fiftyseven': 0,
 'brand_sanrio': 0,
 'brand_save the duck': 0,
 'brand_sc': 0,
 'brand_schiesser': 0,
 'brand_scotch & soda': 0,
 "brand_scotch r'belle": 0,
 'brand_scotch shrunk': 0,
 'brand_seafolly': 0,
 'brand_sense organics': 0,
 'brand_shepherd': 0,
 'brand_shoo pom': 0,
 'brand_simonetta': 0,
 'brand_sisley': 0,
 'brand_skechers': 0,
 'brand_skiny': 0,
 'brand_skip hop': 0,
 'brand_small rags': 0,
 'brand_smiley': 0,
 'brand_smiling shark': 0,
 'brand_småfolk': 0,
 'brand_snapper rock': 0,
 'brand_snowtex': 0,
 'brand_sofie schnoor': 0,
 'brand_soft gallery': 0,
 'brand_someday soon': 0,
 'brand_sometime soon': 0,
 'brand_sonia rykiel': 0,
 'brand_sorel': 0,
 'brand_spider-man': 0,
 'brand_spiderman': 0,
 'brand_sportalm': 0,
 'brand_sproet & sprout': 0,
 'brand_sprox': 0,
 'brand_staccato': 0,
 'brand_star wars': 0,
 'brand_steiff collection': 0,
 'brand_stella mccartney': 0,
 'brand_stella mccartney kids': 0,
 'brand_street life': 0,
 'brand_sugar squad': 0,
 'brand_sunnylife': 0,
 'brand_sunuva': 0,
 'brand_super mario': 0,
 'brand_super mario bros': 0,
 'brand_superfit': 0,
 'brand_superga': 0,
 'brand_superman': 0,
 'brand_supertrash': 0,
 'brand_tao&friends': 0,
 'brand_tao&friends;': 0,
 'brand_ten cate': 0,
 'brand_tenson': 0,
 'brand_teva': 0,
 'brand_the animals observatory': 0,
 'brand_the avengers': 0,
 'brand_the bonnie mob': 0,
 'brand_the brand': 0,
 'brand_the little tailor': 0,
 'brand_the new': 0,
 'brand_the north face': 0,
 'brand_the tiny universe': 0,
 'brand_ticket to heaven': 0,
 'brand_tiffosi': 0,
 'brand_timberland': 0,
 'brand_tinycottons': 0,
 'brand_tobias & the bear': 0,
 'brand_tocoto vintage': 0,
 'brand_tom & drew': 0,
 'brand_tom joule': 0,
 'brand_tom tailor': 0,
 'brand_tommy hilfiger': 0,
 'brand_toms': 0,
 'brand_tootsa macginty': 0,
 'brand_tretorn': 0,
 'brand_trollkids': 0,
 'brand_true north': 0,
 "brand_tumble 'n dry": 0,
 'brand_turtledove': 0,
 'brand_tutu du monde': 0,
 'brand_u.s. polo assn.': 0,
 'brand_ugg': 0,
 'brand_under armour': 0,
 'brand_united colors of benetton': 0,
 'brand_us polo': 0,
 'brand_vans': 0,
 'brand_vaude': 0,
 'brand_veja': 0,
 'brand_velveteen': 0,
 'brand_ver de terre': 0,
 'brand_versace': 0,
 'brand_victoria': 0,
 'brand_viking': 0,
 'brand_vilebrequin': 0,
 'brand_vingino': 0,
 'brand_walking': 0,
 'brand_walking bamboo': 0,
 'brand_walking newborn': 0,
 'brand_wauw capow': 0,
 'brand_wauw capow by bang bang': 0,
 'brand_way ink girl': 0,
 'brand_way.ink': 0,
 'brand_weather  report': 0,
 'brand_wesc': 0,
 'brand_wheat': 0,
 'brand_when watches': 0,
 'brand_white stuff': 0,
 'brand_wolf & rita': 0,
 'brand_wood wood': 0,
 'brand_wynken': 0,
 'brand_young soles': 0,
 'brand_young versace': 0,
 'brand_yporqué': 0,
 'brand_zadig & voltaire': 0,
 'brand_zalando essentials kids': 0,
 'brand_zara': 0,
 'brand_zip and zoe': 0,
 'brand_zunblock': 0,
 'brand_åhléns': 0}
